# Generated by Django 5.2.1 on 2025-05-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='main_team',
            field=models.BooleanField(default=False),
        ),
    ]
