# Generated by Django 5.2.1 on 2025-05-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('pass', 'Pass'), ('tackle', 'Tackle'), ('try', 'Try'), ('kick', 'Kick'), ('penalty', 'Penalty')], max_length=50)),
                ('timestamp', models.TimeField(blank=True, null=True)),
                ('x_coord', models.FloatField(blank=True, null=True)),
                ('y_coord', models.FloatField(blank=True, null=True)),
                ('location_zone', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
