# Generated by Django 5.2.1 on 2025-05-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='opponent_team',
            new_name='team',
        ),
    ]
