# Generated by Django 5.2.1 on 2025-05-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_event_is_opponent_event_alter_event_event_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="event",
            name="phase",
            field=models.PositiveIntegerField(
                blank=True, help_text="Phase of play leading up to event", null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("try", "Try"),
                    ("kick", "Kick"),
                    ("penalty", "Penalty"),
                    ("kickoff", "Kick-off"),
                    ("pass", "Pass"),
                    ("carry", "Carry"),
                    ("run", "Run"),
                    ("tackle", "Tackle"),
                    ("missed_tackle", "Missed Tackle"),
                    ("ruck", "Ruck"),
                    ("maul", "Maul"),
                    ("lineout", "Lineout"),
                    ("lineout_win", "Lineout Win"),
                    ("lineout_loss", "Lineout Loss"),
                    ("scrum", "Scrum"),
                    ("scrum_win", "Scrum Win"),
                    ("scrum_loss", "Scrum Loss"),
                    ("kick_return", "Kick Return"),
                    ("box_kick", "Box Kick"),
                    ("grubber_kick", "Grubber Kick"),
                    ("free_kick", "Free Kick"),
                    ("drop_goal", "Drop Goal"),
                    ("conversion", "Conversion"),
                    ("conversion_missed", "Conversion Missed"),
                    ("penalty_goal", "Penalty Goal"),
                    ("penalty_missed", "Penalty Missed"),
                    ("turnover", "Turnover"),
                    ("knock_on", "Knock-on"),
                    ("forward_pass", "Forward Pass"),
                    ("interception", "Interception"),
                    ("high_tackle", "High Tackle"),
                    ("offside", "Offside"),
                    ("not_releasing", "Not Releasing"),
                    ("holding_on", "Holding On"),
                    ("in_touch", "Ball in Touch"),
                    ("restart", "Restart"),
                    ("injury", "Injury"),
                    ("yellow_card", "Yellow Card"),
                    ("red_card", "Red Card"),
                    ("sin_bin", "Sin Bin"),
                    ("substitution", "Substitution"),
                    ("try_assist", "Try Assist"),
                    ("line_break", "Line Break"),
                    ("defensive_line_break", "Defensive Line Break"),
                    ("advantage", "Advantage"),
                    ("offload", "Offload"),
                    ("foul_play", "Foul Play"),
                    ("referee_call", "Referee Call"),
                    ("timeout", "Timeout"),
                    ("restart_22", "22m Restart"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location_zone",
            field=models.CharField(
                blank=True,
                help_text="Named zone, e.g., '22', 'left wing', etc.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="x_coord",
            field=models.FloatField(
                blank=True,
                help_text="X coordinate, e.g., 0-100 along field length",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="y_coord",
            field=models.FloatField(
                blank=True,
                help_text="Y coordinate, e.g., 0-100 along field width",
                null=True,
            ),
        ),
    ]
